services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  test_runner:
      build: .
      command: pytest tests/test_main.py
      depends_on:
      - mysql
      - redis
      - fastapi
      environment:
      - SKIP_DB_INIT=true
      volumes:
      - .:/code   
